# Generated by Django 5.1.6 on 2026-02-10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("matricula", models.CharField(max_length=20, unique=True)),
                ("data_nascimento", models.DateField(verbose_name="Data de nascimento")),
                ("curso", models.CharField(max_length=100)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Aluno",
                "verbose_name_plural": "Alunos",
                "ordering": ["nome"],
            },
        ),
    ]
